name: Build Case Toggler

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
      
    - name: Build with PowerShell
      run: .\build.ps1
      shell: powershell
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaseToggler-exe
        path: CaseToggler.exe
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./CaseToggler.exe
        asset_name: CaseToggler.exe
        asset_content_type: application/octet-stream