name: Build Case Toggler

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
      
    - name: Build with PowerShell
      run: .\build.ps1
      shell: powershell
      
    - name: Enable .NET Framework 3.5
      run: |
        Enable-WindowsOptionalFeature -Online -FeatureName NetFx3 -All -NoRestart
      shell: powershell
      
    - name: Setup WiX Toolset
      run: |
        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
        Invoke-WebRequest -Uri $wixUrl -OutFile "wix311.exe"
        Start-Process -FilePath "wix311.exe" -ArgumentList "/quiet" -Wait
      shell: powershell
      
    - name: Build MSI Installer
      run: |
        $wixPath = "C:\Program Files (x86)\WiX Toolset v3.11\bin"
        & "$wixPath\candle.exe" "CaseToggler.wxs" -out "dist\CaseToggler.wixobj"
        & "$wixPath\light.exe" "dist\CaseToggler.wixobj" -ext WixUIExtension -out "dist\CaseToggler-Setup-v1.0.0.msi"
      shell: powershell
      
    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaseToggler-exe
        path: CaseToggler.exe
        
    - name: Upload MSI Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaseToggler-msi-installer
        path: dist/CaseToggler-Setup-v1.0.0.msi
        
    - name: Upload Executable to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./CaseToggler.exe
        asset_name: CaseToggler.exe
        asset_content_type: application/octet-stream
        
    - name: Upload MSI Installer to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/CaseToggler-Setup-v1.0.0.msi
        asset_name: CaseToggler-Setup-v1.0.0.msi
        asset_content_type: application/octet-stream