name: Build Case Toggler

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build with PowerShell
      run: .\build.ps1
      shell: powershell
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CaseToggler-exe
        path: CaseToggler.exe
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false