name: Build Case Toggler

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2
      
    - name: Build Application
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        Write-Host "Building Case Toggler..." -ForegroundColor Green
        Get-ChildItem -Force
        .\build.ps1
        if (!(Test-Path "CaseToggler.exe")) { 
          Write-Error "Build failed - executable not found"
          exit 1 
        }
        Write-Host "Build successful!" -ForegroundColor Green
      
    - name: Create dist directory
      run: |
        if (-not (Test-Path "dist")) {
          New-Item -ItemType Directory -Path "dist" -Force
          Write-Host "Created dist directory" -ForegroundColor Green
        }
      shell: powershell
      
    - name: Setup WiX Toolset
      run: |
        Write-Host "Installing WiX Toolset via Chocolatey..." -ForegroundColor Yellow
        
        # Install WiX via chocolatey (pre-installed on GitHub runners)
        choco install wixtoolset -y
        
        # Refresh environment variables
        $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("PATH","User")
        
        # Check multiple possible installation paths
        $possiblePaths = @(
          "C:\Program Files (x86)\WiX Toolset v3.11\bin",
          "C:\Program Files\WiX Toolset v3.11\bin",
          "C:\ProgramData\chocolatey\lib\wixtoolset\tools"
        )
        
        $wixPath = $null
        foreach ($path in $possiblePaths) {
          if (Test-Path "$path\candle.exe") {
            $wixPath = $path
            Write-Host "Found WiX at: $wixPath" -ForegroundColor Green
            break
          }
        }
        
        if (-not $wixPath) {
          Write-Host "Searching for candle.exe in system..." -ForegroundColor Yellow
          $candleExe = Get-ChildItem -Path "C:\" -Name "candle.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($candleExe) {
            $wixPath = Split-Path $candleExe.FullName
            Write-Host "Found WiX at: $wixPath" -ForegroundColor Green
          } else {
            Write-Error "WiX installation failed - candle.exe not found anywhere"
            exit 1
          }
        }
        
        # Set environment variable for next steps
        echo "WIX_PATH=$wixPath" >> $env:GITHUB_ENV
        Write-Host "WiX Toolset installed successfully at: $wixPath" -ForegroundColor Green
      shell: powershell
      
    - name: Build MSI Installer
      run: |
        $wixPath = $env:WIX_PATH
        Write-Host "Using WiX path: $wixPath" -ForegroundColor Yellow
        
        Write-Host "Building MSI installer..." -ForegroundColor Yellow
        
        # Compile WiX source
        & "$wixPath\candle.exe" "CaseToggler.wxs" -out "dist\CaseToggler.wixobj"
        if ($LASTEXITCODE -ne 0) {
          Write-Error "WiX compilation failed"
          exit 1
        }
        
        # Link to create MSI
        & "$wixPath\light.exe" "dist\CaseToggler.wixobj" -ext WixUIExtension -out "dist\CaseToggler-Setup-v1.0.0.msi"
        if ($LASTEXITCODE -ne 0) {
          Write-Error "WiX linking failed"
          exit 1
        }
        
        # Verify MSI was created
        if (-not (Test-Path "dist\CaseToggler-Setup-v1.0.0.msi")) {
          Write-Error "MSI creation failed - file not found"
          exit 1
        }
        
        Write-Host "MSI installer created successfully" -ForegroundColor Green
      shell: powershell
      
    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaseToggler-exe
        path: CaseToggler.exe
        
    - name: Upload MSI Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaseToggler-msi-installer
        path: dist/CaseToggler-Setup-v1.0.0.msi
        
    - name: Upload Executable to Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CaseToggler.exe
          dist/CaseToggler-Setup-v1.0.0.msi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}